export enum EDITOR_ACTION_ENUM {
  ADD_ELEMENT = 'ADD_ELEMENT',
  UPDATE_ELEMENT = 'UPDATE_ELEMENT',
  DELETE_ELEMENT = 'DELETE_ELEMENT',
  SELECT_ELEMENT = 'SELECT_ELEMENT',
  UNDO = 'UNDO',
  REDO = 'REDO',
  TOGGLE_LIVE_MODE = 'TOGGLE_LIVE_MODE',
  TOGGLE_PREVIEW_MODE = 'TOGGLE_PREVIEW_MODE',
  CHANGE_SIDEBAR_TAB = 'CHANGE_SIDEBAR_TAB',
}
