export enum ELEMENT_TYPE_ENUM {
  BODY = 'BODY',
  CONTAINER = 'CONTAINER',
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  '2COLUMN' = '2COLUMN',
  HR = 'HR',
  BUTTON = 'BUTTON',
  ROW = 'ROW',
  COLUMN = 'COLUMN',
  HEADING = 'HEADING',
  LINK = 'LINK',
}
